import {StyleSheet} from "react-native";
import {theme} from "@/theme";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.colors.background,
        padding: theme.spacing.medium,
        justifyContent: 'center',
    },
    topSection: {
        flex: 0.3,
        backgroundColor: theme.colors.cardBackground,
        borderRadius: theme.borderRadius.medium,
        marginBottom: theme.spacing.medium,
        marginHorizontal: theme.spacing.small,
    },
    card: {
        backgroundColor: theme.colors.cardBackground,
        borderRadius: theme.borderRadius.medium,
        padding: theme.spacing.medium,
        marginBottom: theme.spacing.medium,
        marginHorizontal: theme.spacing.small,
    },
    news: {
        flex: 0.7,
        backgroundColor: theme.colors.cardBackground,
        borderRadius: theme.borderRadius.medium,
        padding: theme.spacing.medium,
        marginBottom: theme.spacing.medium,
        marginHorizontal: theme.spacing.small,
    },
    sectionTitle: {
        color: '#ffffff',
        fontSize: theme.fonts.large,
        fontWeight: 'bold',
        marginBottom: theme.spacing.small,
    },
    input: {
        backgroundColor: '#333333',
        color: '#ffffff',
        borderRadius: theme.borderRadius.small,
        padding: theme.spacing.small,
        marginBottom: theme.spacing.small,
    },
    symbol: {
        fontSize: theme.fonts.large,
        fontWeight: 'bold',
        color: '#ffffff',
    },
    generalText: {
        fontSize: theme.fonts.regular,
        color: theme.colors.whiteText,
    },
    errorText: {
        color: theme.colors.onError,
    },
    appTitle: {
        fontSize: theme.fonts.titleLarge,
        fontWeight: 'bold',
        color: theme.colors.text,
        marginBottom: theme.spacing.small,
        textAlign: 'center',
    },
    slogan: {
        fontSize: theme.fonts.regular,
        color: theme.colors.subtitle,
        marginBottom: theme.spacing.small,
        textAlign: 'center',
        fontWeight: 'bold',
    },
    button: {
        backgroundColor: theme.colors.primary,
        borderRadius: theme.borderRadius.extraLarge,
        paddingVertical: theme.spacing.medium,
        paddingHorizontal: theme.spacing.large,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: theme.spacing.small,
        width: '80%',
        alignSelf: 'center',
        shadowColor: theme.colors.boxShadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
        elevation: 5,
    },
    buttonText: {
        color: theme.colors.whiteText,
        fontSize: theme.fonts.regular,
        fontWeight: 'bold',
    },
    createButton: {
        backgroundColor: theme.colors.secondary,
        marginBottom: theme.spacing.medium,
    },
    createButtonText: {
        color: theme.colors.text,
    },
    orTextContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginVertical: theme.spacing.small,
    },
    orText: {
        color: theme.colors.subtitle,
        fontSize: theme.fonts.regular,
        marginHorizontal: theme.spacing.small,
        verticalAlign: 'middle',
    },
    orTextLine: {
        flex: 0.3,
        height: 1,
        backgroundColor: theme.colors.subtitle,
    },
    socialContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
    },
    socialButton: {
        borderWidth: 1,
        backgroundColor: theme.colors.primaryContainer,
        borderRadius: theme.borderRadius.extraLarge,
        padding: theme.spacing.small,
        alignItems: 'center',
        justifyContent: 'center',
        width: 100,
        height: 60,
        marginHorizontal: theme.spacing.medium,
    },
    socialIcon: {
        width: 24,
        height: 24,
    },
    logo: {
        width: 150,
        height: 150,
        marginBottom: theme.spacing.medium,
        alignSelf: 'center',
    },
    centerContent: {
        flex: 0.7,
        justifyContent: 'center',
        alignItems: 'center',
    },
    header: {
        color: theme.colors.whiteText,
        fontSize: theme.fonts.headerLarge,
        marginVertical: theme.spacing.small,
        fontWeight: 'bold',
    },
    switchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#2D2D2D',
        padding: theme.spacing.small,
        borderRadius: theme.spacing.small,
        marginVertical: theme.spacing.small,
    },
    switchLabel: {
        color: theme.colors.whiteText,
        fontSize: theme.fonts.regular,
    },
    signOutButton: {
        backgroundColor: '#2D2D2D',
        padding: theme.spacing.medium,
        borderRadius: theme.spacing.small,
        marginTop: theme.spacing.large,
        alignItems: 'center',
    },
    signOutButtonText: {
        color: theme.colors.error,
        fontSize: theme.fonts.regular,
        fontWeight: 'bold',
    },
    settingsSection: {
        marginVertical: theme.spacing.large,
        paddingHorizontal: theme.spacing.large,
    },
    settingsOption: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: theme.spacing.medium,
        paddingHorizontal: theme.spacing.medium,
        borderBottomWidth: 1,
        backgroundColor: theme.colors.cardBackground,
    },
    logOutSection: {
        marginVertical: theme.spacing.large,
        paddingHorizontal: theme.spacing.large,
    },
    settingsContainer: {
        paddingVertical: theme.spacing.small,
        flex: 1,
        backgroundColor: theme.colors.background,
        padding: theme.spacing.medium,
    },
    settingsGroup: {
        backgroundColor: theme.colors.cardBackground,
        borderRadius: theme.borderRadius.medium,
        overflow: 'hidden',
    }
});